[workspace]
name = "litodoc"
members = ["core", "web", "protocol", "book", "tests"]
default-members = ["book"]

[workspace.package]
version = "0.1.0"

[workspace.dependencies.litodoc-core]
path = "core"

[workspace.dependencies.litodoc-web]
path = "web"

[workspace.dependencies.rstd-std]
git = "https://github.com/litocpp/rstd.git"

[workspace.dependencies.rstd-json]
git = "https://github.com/litocpp/rstd.git"

[workspace.dependencies.rstd-toml]
git = "https://github.com/litocpp/rstd.git"

[workspace.dependencies.rstd-argparse]
git = "https://github.com/litocpp/rstd.git"

[workspace.dependencies.rstd-test]
git = "https://github.com/litocpp/rstd.git"

[profile]
exceptions = false
rtti = false
