[package]
name = "litodoc-core"
version.workspace = true

[lib]
name = "litodoc-core"
module = "lito.doc"
archive = "lito.doc"
sources = [
  "src/site/html.cppm",
  "src/site/templates/mod.cppm",
  "src/site/frontend_manifest.cppm",
  "src/site/frontend/mod.cppm",
  "src/site/publication.cppm",
  "src/site/lib.cppm",
  "src/doc/model.cppm",
  "src/doc/database.cppm",
  "src/doc/data/mod.cppm",
  "src/doc/markdown.cppm",
  "src/doc/render.cppm",
  "src/doc/publish.cppm",
  "src/doc/lib.cppm",
  "src/book/model.cppm",
  "src/book/project.cppm",
  "src/book/summary.cppm",
  "src/book/markdown.cppm",
  "src/book/graph.cppm",
  "src/book/data.cppm",
  "src/book/render.cppm",
  "src/book/lib.cppm",
]

[dependencies.rstd-std]
workspace = true
visibility = "public"

[dependencies.rstd-json]
workspace = true
visibility = "private"

[dependencies.rstd-serde]
workspace = true
visibility = "private"

[dependencies.rstd-toml]
workspace = true
visibility = "private"

[dependencies.licrypto]
workspace = true
visibility = "private"
