[package]
name = "litobook"
version.workspace = true
language = "cpp"
minimum-standard = "c++20"

[[bin]]
name = "litobook"
module = "litobook.executable"
sources = ["src/tool.cppm", "src/main.cppm"]

[dependencies.litodoc-core]
workspace = true
visibility = "private"

[dependencies.litodoc-web]
workspace = true
visibility = "private"

[dependencies.rstd-std]
workspace = true
visibility = "private"

[dependencies.rstd-argparse]
workspace = true
visibility = "private"
